### ISSUE TITLE
why I can't customize the `signin` URL

### ISSUE THREAD

**Issue by Airren** [casdoor/casdoor-react-sdk#11]
<img width="1042" alt="image" src="https://github.com/casdoor/casdoor-react-sdk/assets/14846116/eacdbed8-4c7e-4fdb-b59c-8567af374341">

**Comment by hsluoyz** [comment]
@Airren can you make a PR to fix it?

**Comment by HuckOps** [comment]
This url must be `${server_url}/api/signin`
I will take some time to fix this issue and provide customizable formal variables

**Comment by hsluoyz** [comment]
This code doesn't exist any more. The issue is also not valid now.
